apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.51.0
        # Database is not HA
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8081
        #   failureThreshold: 50
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "3Gi"
        ports:
          - containerPort: 8081
      initContainers:
      - name: chmod
        image: alpine:3.17.2
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        command: ["/bin/sh", "-c", "chown -R 200:200 /nexus-data"]
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-data-claim
      priorityClassName: production-service
      terminationGracePeriodSeconds: 60 # 1 minute
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
spec:
  type: ClusterIP
  selector:
    app: nexus
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-claim
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: 10Gi
