apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.44.0
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          failureThreshold: 20
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        - name: sonatype-work
          mountPath: /sonatype-work
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "3Gi"
        ports:
          - containerPort: 8081
      initContainers:
      - name: chmod
        image: alpine:3.17.0
        volumeMounts:
        - name: sonatype-work
          mountPath: /sonatype-work
        command: ["chmod", "777", "/sonatype-work"]
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-data-claim
      - name: sonatype-work
        emptyDir: {}
      priorityClassName: production-service
      terminationGracePeriodSeconds: 60 # 1 minute
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
spec:
  type: ClusterIP
  selector:
    app: nexus
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-claim
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: 10Gi
