apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser
        volumeMounts:
        - mountPath: /srv/test
          name: test
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "500Mi"
        ports:
        - containerPort: 80
      volumes:
      - name: test
        persistentVolumeClaim:
          claimName: test-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
