apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-editor
  namespace: REPLACE_ME
spec:
  selector:
    matchLabels:
      app: data-editor
  replicas: 1
  template:
    metadata:
      labels:
        app: data-editor
    spec:
      containers:
      - name: data-editor
        image: ubuntu@sha256:889d056d5c6c0bfb55789ff3710681d68e50713cb562d2196dc07110599c7a6f
        command: [ "sleep", "99999999" ]
        volumeMounts:
        - name: data
          mountPath: /mnt
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: REPLACE_ME
