apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-editor
  namespace: REPLACE_ME
spec:
  selector:
    matchLabels:
      app: data-editor
  replicas: 1
  template:
    metadata:
      labels:
        app: data-editor
    spec:
      containers:
      - name: data-editor
        image: ubuntu@sha256:eecba05a9ccbc219cb0f0dd280034c6ee1aab0b00b458e680f9c4efc6ca3feda
        command: [ "sleep", "99999999" ]
        volumeMounts:
        - name: data
          mountPath: /mnt
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: REPLACE_ME
