apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-editor
  namespace: REPLACE_ME
spec:
  selector:
    matchLabels:
      app: data-editor
  replicas: 1
  template:
    metadata:
      labels:
        app: data-editor
    spec:
      containers:
      - name: data-editor
        image: ubuntu@sha256:61ebaa5cc23ca45450db85eac015435199ec569e28ec222ea13f2aed2110b8a6
        command: [ "sleep", "99999999" ]
        volumeMounts:
        - name: data
          mountPath: /mnt
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: REPLACE_ME
