apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-editor
  namespace: REPLACE_ME
spec:
  selector:
    matchLabels:
      app: data-editor
  replicas: 1
  template:
    metadata:
      labels:
        app: data-editor
    spec:
      containers:
      - name: data-editor
        image: ubuntu@sha256:5d070ad5f7fe63623cbb99b4fc0fd997f5591303d4b03ccce50f403957d0ddc4
        command: [ "sleep", "99999999" ]
        volumeMounts:
        - name: data
          mountPath: /mnt
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: REPLACE_ME
