kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-network-policy
  namespace: acrylicstyle-ssh
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - ports:
    - port: 22
      protocol: TCP
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.1.0.0/16 # microk8s pod ip range
        - 10.0.0.0/16 # wireguard ip range
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
